sudo: required

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - NODE_RELEASE=8.x

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - travis_retry composer self-update

install:
  - composer install
  - yarn

script:
  - vendor/bin/phpunit
  - yarn eslint